### ISSUE TITLE
Faulty availability shown when filter active

### ISSUE THREAD

**Issue by NeoScaler** [johan12345/EVMap#100]
When I use an active filter for example filtering only chargers with min. 100 kw, there is always a green "0/0" shown in the bottom bar when I click on a charger (Ionity Weißkirchen for example). When I enter the details, I see the real availability (3/4).

Does not happen without filter, there it is working fine.

**Comment by johan12345** [comment]
I think this has nothing to do with the filter by power, but rather a filter by plug type (e.g. CCS). Correct?

**Comment by NeoScaler** [comment]
Could also be the cause. I am filtering for power and CCS / Type 2 plugs, yes.

**Comment by johan12345** [comment]
Okay, in that case 6ec44bb should fix it. The availability shown at the bottom bar takes into account the filters (e.g. when you filter by CCS it only shows CCS plugs) - and with the changes introduced in the beta version for compatibility with OpenChargeMap, each plug type now has an API-internal ID and a common name, which need to be converted correctly for filtering the availability.
