### ISSUE TITLE
Request: CAD currency

### ISSUE THREAD

**Issue by Kreuger** [johan12345/EVMap#103]
Hey man. Im playing around with the app now that you have added support for Open Charge Map. But Ive noticed that the CAD isnt available as a currency yet. Would be awesome to see it added.

**Comment by johan12345** [comment]
Hi! The currencies are currently used for the price comparison feature, which is based on the data from Chargeprice.app. Have you seen that work for any of the Canadian chargers so far? If yes, I can of course also add CAD to the currencies - otherwise it's probably not yet very helpful.

**Comment by Kreuger** [comment]
Im not sure what you mean. I looked at their site and couldnt see any chargers at all.

**Comment by johan12345** [comment]
I mean this button in the app:
![Screenshot_20210726-221601.png](https://user-images.githubusercontent.com/5310424/127053221-9e570fae-e229-47d2-b107-13a709756f0c.png)
This is the only place where the currency selected in the settings would be used.

As far as I know, OpenChargeMap support is still in beta at the Chargeprice.app API, and I don't think they have prices for any of the American charger networks so far.

**Comment by Kreuger** [comment]
Yeah it doesnt work.

**Comment by johan12345** [comment]
In the meantime I have heard back from the people at Chargeprice.app, they support no countries outside Europe so far (see also https://github.com/johan12345/EVMap/issues/117). So I'll disable the price comparison button in these countries for now.

As written above, as long as we have no data source for charging prices in Canada, it does not really make sense to add CAD to the list. So I'll close this for now.
