### ISSUE TITLE
App not supported on Android auto for Phone screens

### ISSUE THREAD

**Issue by ABr751** [johan12345/EVMap#104]
https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead.phonescreen
I was testing the app flow when connected to a head unit with the above app unfortunately, it's not  supported on the above app. I think we need to add some meta-data in android manifest file regarding the navigation and charging.

**Comment by johan12345** [comment]
Third-party Android Auto navigation and charging apps are not supported on phone screens at all, as far as I know - only on car head units.

**Comment by johan12345** [comment]
See also https://issuetracker.google.com/issues/179172845
