### ISSUE TITLE
An adaptive problem

### ISSUE THREAD

**Issue by yuhuitech** [johan12345/EVMap#106]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the welcome page, **a part of text seems to be tangled with an animation**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 0.8.3, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that the texts on the welcome page should be **fully** seprated from the animation on it.

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. open EVMap(for the very first time)
3. this error could be seen(Screenshot 1)
4. if you scroll to next page, another similar problem could also be seen(Screenshot 2)

**Screenshots**

Screenshot 1:

<img src="https://user-images.githubusercontent.com/25502419/128806234-0574c328-4e51-4fcc-a3fd-31c5bc4364de.png" alt="Screenshot_1628565862 copy" width="250"/>

Screenshot 2:

<img src="https://user-images.githubusercontent.com/25502419/128806237-7ec67c5e-024a-468d-b02f-061a90a1a834.png" alt="Screenshot_1628565862 copy" width="250"/>

**Environment**

1. Version of EVMap : 0.8.3
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by johan12345** [comment]
Hi! Thanks for the report - this is definitely a bug, I didn't test these intro screens with so large scaling and font size. The layout of the intro screen is loosely based on [the design guidelines here](https://material.io/design/communication/onboarding.html#top-user-benefits-model), but probably the margins between the elements need to be reduced when not enough space is available on the screen.

Would you like to take a look if you can improve it?

**Comment by yuhuitech** [comment]
OK, I will try to improve it. Thank you so much!
