### ISSUE TITLE
Could not load charging stations

### ISSUE THREAD

**Issue by mtris** [johan12345/EVMap#142]
![2021102901](https://user-images.githubusercontent.com/24400330/139508053-296cd0d3-4352-4ca2-be24-685890378668.png)
![2021102902](https://user-images.githubusercontent.com/24400330/139508073-e8875738-f944-402d-88af-5f06efacc939.png)
Dear EVMap Team:
I went on to the app tonight (29-Oct-2021 22:00 GMT) and  I see the map is filling in, but it is not loading the charging stations. I receive the message at the bottom, Could not load charging stations, hit RETRY several times, but it would not work. I also tried uninstalling the app and reinstalling the previous version. Any help or suggestions are appreciated. Thank you for your time and for a great app. Sincerely,
(EVMap v1.1.0 (from F-Droid))

**Comment by johan12345** [comment]
Thanks for the report! Right now it is working fine for me, so maybe this was a short-term server side problem at OpenChargeMap or GoingElectric (depending on which data source you have selected)?

**Comment by mtris** [comment]
Hello: I am using Open Charge Map and it's improved significantly. Thank you very much for the reply.

**Comment by johan12345** [comment]
Great! You can always also check on the OpenChargeMap website (https://map.openchargemap.io/) - if that doesn't work it's most probably an issue on their side and not EVMap's fault.
