### ISSUE TITLE
Show charge amount and average charge speed on price page

### ISSUE THREAD

**Issue by cremor** [johan12345/EVMap#171]
In addition to charge times, https://www.chargeprice.app also shows charge amounts in kWh and average charge speeds in kW for the chosen car and charge range. It would be great if EVMap could show this information too.

**Comment by cremor** [comment]
@johan12345 I've now tested version 1.3.3. I think there is a bug in this new feature. EVMap always shows the max charge speed of the charging point in this new average charge speed label. But this is not useful, it should show the average charge speed that can actually be reached by the configured car at this charge point (as shown by chargeprice.app).
The charge amount in kWh and charge durations are shown correctly.

**Comment by johan12345** [comment]
Ah, thanks. Right, it seems the „power“ field that we get from Chargeprice just gives the maximum power. For the average power we need the charged energy divided by the duration. Should be fixed when the next update is released :)
