### ISSUE TITLE
GoingElectric returns HTTP error 431 when filtering for all networks except one

### ISSUE THREAD

**Issue by tretkowski** [johan12345/EVMap#174]
Disabling "Tesla Supercharger" in networks ("Verbünde") results in an error: "Could not load charging stations"

**Comment by johan12345** [comment]
Hm, I just tested this, it seems the GoingElectric server is responding with an HTTP error 431 (Request Header Fields Too Large) for this query, as the HTTP GET query string now contains a list of all the networks except Tesla Supercharger, which is pretty long. Let's see if I can change this into a POST request, which should be able to take more data.

**Comment by johan12345** [comment]
Yep, that seems to work. Thanks for reporting!
