### ISSUE TITLE
Android Auto: Nearby chargers loading forever

### ISSUE THREAD

**Issue by J0B10** [johan12345/EVMap#187]
On my `Fiat 200e (2020)` the "nearby chargers" view does not show any charging stations, instead it keeps on loading.

After about a minute I closed it as it still did not load.

![grafik](https://user-images.githubusercontent.com/17405009/176714716-aec6cac6-e13d-4b51-86ab-a0b6bc0ced05.png)
_the photo was taken right next to a charging point_

I till now have no experience with debugging on Android Auto.  But if you need some more information for debugging, let me know what you need and how I can obtain it (or a link to a guide) and I'll try my best.

Also huge thanks for developing and maintaining this great app! 👍

**Comment by johan12345** [comment]
Thanks!

Have you tried the current [beta version](https://play.google.com/apps/testing/net.vonforst.evmap)? It should be much better the changes in e182f8ae.

**Comment by johan12345** [comment]
Hmm, `1.3.2` should already have those changes that I mentioned... However `1.3.3` does include some more changes to the Android Auto app which might have an influence. It has now been reviewed by Google, so should probably be available within a day or so.

**Comment by PulsarFX** [comment]
had the same issues, which are now gone.

**Comment by J0B10** [comment]
Yeah, sorry for not reporting back, I just forgot about it 🤦‍♂️ 

Seems to also be fixed for me.
