### ISSUE TITLE
Availabilty quick info filters plugs if power exactly matches min power from filter

### ISSUE THREAD

**Issue by cremor** [johan12345/EVMap#194]
1. Create a filter for "Minimum power x kW".
2. Select a charging station on the map.
3. Check the availability quick info. It will not include plugs with exactly x kW power - so the min value set in the filter. This can lead to "0/0" availability being shown in red if "x" is the maximum power of that charging station.

In other words: The availabilty quick info checks for "plug power > filter min power" instead of "plug power >= filter min power"

I can only confirm this bug for EnBW availabilty data. Unsure if other availability providers are affected too.

App version 1.3.3

**Comment by johan12345** [comment]
Thanks! Should be fixed with https://github.com/johan12345/EVMap/commit/3ac7b4aaee6ebf43b92678f073ef7ea1698c17f1
