### ISSUE TITLE
Import route from Google Maps?

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#20]
> Das Killer Feature für mich wäre wenn ich meine in Google Maps geplante Route importieren könnte und somit eine schnelle Visualisierung der Säulen entlang der Route hätte. Mit anklicken entlang der Route könnte man die Kilometer seit Start/bis Ziel darstellen für eine manuelle Ladeplanung.

https://www.goingelectric.de/forum/viewtopic.php?p=1255223#p1255223

**Comment by TweetsOfNiklas** [comment]
But isn't this just abetterrouteplanner? Or should it only be manual?

**Comment by johan12345** [comment]
Right, it is close to what ABRP offers, just manual. Thus I'm not sure if I want this, definitely not very high priority.

**Comment by johan12345** [comment]
closing because I don't really see how this would work (and as there is already ABRP for this)
