### ISSUE TITLE
persistent Android Auto notification: use proper app icon

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#201]
Minor cosmetic issue - the icon is currently just a white blob.

**Comment by PulsarFX** [comment]
That is, on Android 11 ( LineageOS)
On Android 12 it shows correctly, colored with the green marker. (Samsung UI)

**Comment by johan12345** [comment]
Ah interesting - it has always been just the white blob for me (on Pixel devices with different Android versions) - then that is probably not due to the Android version, but because Samsung's UI removes Android's requirement for notification icons to be black & white 😄

**Comment by PulsarFX** [comment]
To not have a blob you need to use a b/w icon with transparent background. 
I used https://romannurik.github.io/AndroidAssetStudio/index.html  for my icons.
