### ISSUE TITLE
Gmaps map source doesn't load

### ISSUE THREAD

**Issue by PulsarFX** [johan12345/EVMap#203]
behavior:
- only a white screen is shown. 
- Google logo on bottom left, scale bottom right.
- zoom doesn't work (no change in scale), no map pins are shown.

context:
- Samsung with Android 12, EvMap 1.3.5-google
- All rights provided via android app settings.

- mapbox on the other hand loads instantly.

**Comment by johan12345** [comment]
I have seen this sometimes occur after first launch - and no idea what causes it (bug in Google Maps SDK?)... But it usually works after killing and restarting the app.

**Comment by PulsarFX** [comment]
A Screenshot 
![Screenshot_20220807-230050_EVMap_resized](https://user-images.githubusercontent.com/4960210/183311034-7011d8db-89cc-47e8-a0c8-3eaa3af4644d.jpg)

Killing the app sometimes work. Did so on my lineageOS device but not on the Samsung

**Comment by PulsarFX** [comment]
I've now returned from the dropbox test version (non-signed) to the gplay Version and gmaps loads instantly again ....

**Comment by johan12345** [comment]
Ah... Right, if this just occurs in the Dropbox version it might really be just a signature issue. The Google Maps API key is restricted to certain signatures, and if the signature doesn't match the map will not load.

But the Dropbox version was only meant for testing AA, so it doesn't matter in this case.
