### ISSUE TITLE
FDroid link broken

### ISSUE THREAD

**Issue by mycae** [johan12345/EVMap#204]
The link on https://github.com/johan12345/EVMap to the fdroid repository (https://f-droid.org/repository/browse/?fdid=net.vonforst.evmap) is no longer working.

I checked in fdroid's archive and main repositories, but EVMap appears to no longer be available.

**Comment by johan12345** [comment]
This is due to #197, which should now be fixed (see also https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11527). I guess we just need to wait a couple more days for their buildserver to pick it up.

**Comment by johan12345** [comment]
In the meantime you can also download APKs at https://github.com/johan12345/EVMap/releases (however they are of course not signed with a different certificate, it you want to install an F-Droid or Play Store version later you'll first have to uninstall this one).

**Comment by johan12345** [comment]
Now the F-Droid link works again: https://f-droid.org/packages/net.vonforst.evmap/
