### ISSUE TITLE
Visual bug in chargeprice integration: advertisement for provider

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#206]
The Eborn provider seems to be "advertised" by chargeprice on some chargers (yellow background and additionnal green info box). This leads to "2" issues:

- in dark mode the white text on yellow background looks odd (not enough contraste), so the look itself would need to be fixed
- moreover, wouldn't it be better to treat all networks the "same" and remove the advertising for EVmap to remain more neutral?

**Comment by johan12345** [comment]
Thanks for the report!

> * in dark mode the white text on yellow background looks odd (not enough contraste), so the look itself would need to be fixed

Yes, I will take a look into this.

> * moreover, wouldn't it be better to treat all networks the "same" and remove the advertising for EVmap to remain more neutral?

The advertising supports the development of EVMap by lowering the costs I need to pay for the Chargeprice API, see also here: https://evmap.vonforst.net/en/chargeprice_faq.html
The advertising does not affect the sorting of providers though, they are still ordered by increasing price (except that the ones selected under "my plans" are moved above the others).

**Comment by Altonss** [comment]
> Thanks for the report!
> 
> > * in dark mode the white text on yellow background looks odd (not enough contraste), so the look itself would need to be fixed
> 
> Yes, I will take a look into this.
> 
> > * moreover, wouldn't it be better to treat all networks the "same" and remove the advertising for EVmap to remain more neutral?
> 
> The advertising supports the development of EVMap by lowering the costs I need to pay for the Chargeprice API, see also here: https://evmap.vonforst.net/en/chargeprice_faq.html The advertising does not affect the sorting of providers though, they are still ordered by increasing price (except that the ones selected under "my plans" are moved above the others).

Thanks for the explanation, I did not know :) So I guess just an improvement of the visual aspect would be great!
