### ISSUE TITLE
App zooms out too much after charge prize screen 

### ISSUE THREAD

**Issue by PulsarFX** [johan12345/EVMap#213]
- zoom into the map to get pins instead of dots
- look at details of a charger
- go back -  all fine
- look again to the details of a charger
- now do price calculation
- go back to map -  now it is zoomed out way to far, so only dots are visible. That's no fun in big cities

V1.3.6- google

**Comment by johan12345** [comment]
I can't reproduce this in the current version 1.3.7-google - for me, the map position stays exactly the same. Can you update and check if this still occurs for you?

**Comment by PulsarFX** [comment]
I wrote 1.3.6 but it actually happened on 1.3.7

Ah I missed a step.  You've got to first do a search for a location (preferably in a big city). Then look at a chargers  details, open the charge prize calculation and then go back to the map. 

Also I noticed that the top buttons disappear on the charger details after closing the charge prize page

**Comment by johan12345** [comment]
Ah, in that case I can reproduce it, yes. The search result seems to override the saved previous map position when the map view gets recreated. I'll take a look.
