### ISSUE TITLE
Currency overlay flashing repeatedly

### ISSUE THREAD

**Issue by comradekingu** [johan12345/EVMap#219]
In what I imagine to be in very epileptic fashion,
the currencies are flickering when opened.

Version 1.3.7 from F-Droid on LineageOS 17.1.

**Comment by johan12345** [comment]
What screen are you referring to exactly? You mean the selection of currency under settings -> price comparison? Or do you mean *map markers* instead of currencies?

**Comment by Altonss** [comment]
> Sorry. It is the one in Settings → Price comparison → Currency.
> Will try to confirm on a different device.

I don't see this on my device (Android 12)

**Comment by comradekingu** [comment]
Are you running the F-Droid build?
I am also getting flashing of the 50 km marker on the map if "could not load stations". Goes away with Wi-Fi Internet established.

**Comment by johan12345** [comment]
As neither I nor @Altonss could reproduce this and nobody else complained so far, I'd suspect this to be a graphics bug in your LineageOS build rather than an app bug....
Please reopen in case anyone can reproduce this on a different device.
