### ISSUE TITLE
Highlighting of "my charging plans" Broken? 

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#221]

**Comment by Altonss** [comment]
Do you mean the text "(will be highlighted...)" in the settings or the highlight color?

**Comment by Altonss** [comment]
Because I now noticed there is no big difference between the "ad" highlighted plans and the highlighted "my plan" in dark mode: maybe contrast/differentiation is needed :)

**Comment by johan12345** [comment]
I mean the highlight color itself, I currently see no highlight at all in version 1.3.8.

**Comment by Altonss** [comment]
> I mean the highlight color itself, I currently see no highlight at all in version 1.3.8.

Me too, that's probably why the contrast between the 2 is bad

**Comment by cremor** [comment]
@johan12345 Does "highlighting" for you also include the sort order of the tariffs, or just a background or something like that? Because I noticed that in 1.3.8 my tariffs are not shown at the top of the tariff list any more. Is that fixed too?

**Comment by johan12345** [comment]
Yes, that was the same issue in this case
