### ISSUE TITLE
Connector switch while in price comparison broken (very slow)

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#222]

**Comment by johan12345** [comment]
Hm, I can't reproduce that on my side.

**Comment by Altonss** [comment]
It is very slow to switch and during this time both connectors are selected

**Comment by Altonss** [comment]
This does not happen on all chargers somehow :thinking: 
I happened for me with this charger for example: "Aire de Hardivilliers, Total EV Charge"...

**Comment by Altonss** [comment]
> This does not happen on all chargers somehow thinking I happened for me with this charger for example: "Aire de Hardivilliers, Total EV Charge"...

On this charger, the following happens:
- after clicking the new connector, it is correctly selected
- but the old connector remains selected and with it it's old data
- after a short time (maybe 1s) only the new connector is selected, at the same time it's data gets displayed

Maybe it would be better to simply select the new connector and display a loading wheel... Idk

**Comment by johan12345** [comment]
Hm okay, it's usually much faster than 1s for me, but that may depend on the phone. It's not loading any data from the network or local storage though at this point - switching the connector should simply mean displaying different data that's already in the RAM. I think for some reason generating the layout of all those rows for the prices is slow, which causes the CPU to hang...

**Comment by Altonss** [comment]
> it's usually much faster than 1s for me, but that may depend on the phone

It's strange because my phone is pretty fast :thinking:

**Comment by Altonss** [comment]
But it's not consistent, it isn't as slow every time.
Another charger which is also very slow to switch: Ionity Holiday Inn Calais (FR)

**Comment by johan12345** [comment]
Ah, I think I found the issue: Due to the way the views were set up in the ChargepriceFragment, it was trying to build the layout for all rows at once, not just for those which are currently visible. That can of course be pretty slow.

**Comment by Altonss** [comment]
Thanks a lot for the fix :heart:
