### ISSUE TITLE
Filters displayed on the maps charger filter selection is broken

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#230]
- deleted filters are displayed
- when more than 2 filters those are not displayed, and even do not appear when other are deleted or the order of filters rearranged

**Comment by johan12345** [comment]
Could it be that this is actually the same problem that I mentioned in my comment in #231 ? If you created a filter with the same name for both data sources and delete it for one of them, it will still be there for the other data source. And as the data source currently doesn't update on the map view until the app is restarted this is slightly confusing.

**Comment by johan12345** [comment]
As I suppose this is the same issue as mentioned in #231. Please reopen if it still occurs after the next update.

**Comment by Altonss** [comment]
> As I suppose this is the same issue as mentioned in #231. Please reopen if it still occurs after the next update.

Thanks a lot for the fix :) Will test it out as soon as it is available on F-Droid :)
