### ISSUE TITLE
Update list of allowed countries for chargeprice

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#234]
- [ ] Finland
- [ ] Lithuania
- [ ] Lattiva
- [ ] Estonia
- [ ] Liechtenstein
- [ ] Romania
- [ ] Slovakia
- [ ] Poland
- [ ] Serbia
- [ ] Bulgaria
- [ ] Kosovo
- [ ] Montenegro
- [ ] Albania
- [ ] Greece
- [ ] Portugal
- [ ] Iceland

**Comment by johan12345** [comment]
Where did you get this list from? Is this the list of countries where Chargeprice shows charging stations on the map, or where they actually have reliable data about prices (including plans from local providers)?

For example it seems that Chargeprice doesn't have any pricing information for most chargers in Iceland (except for Tesla Superchargers and Virta). Same for Portugal, where Shell Recharge is usually the only provider listed.

**Comment by Altonss** [comment]
> Where did you get this list from? Is this the list of countries where Chargeprice shows charging stations on the map, or where they actually have reliable data about prices (including plans from local providers)?
> 
> For example it seems that Chargeprice doesn't have any pricing information for most chargers in Iceland (except for Tesla Superchargers and Virta). Same for Portugal, where Shell Recharge is usually the only provider listed.

I looked on the Chargeprice map, and every country that is cited in my first post contains chargers with chargeprice price comparaison support

**Comment by johan12345** [comment]
Yeah, but if you actually try to get prices for those chargers you will often see that there is not much useful information there.

**Comment by Altonss** [comment]
> Yeah, but if you actually try to get prices for those chargers you will often see that there is not much useful information there.

If I remember correctly I found for each country a charger that has at least more than 2 pricing options... so it is useful and will probably expand in the future

**Comment by Altonss** [comment]
For Iceland: Virta seems to have a lot of chargers there! (And for the other chargepoints it often is written soon)
For Portugal: This charger for example contains a lot of different tarifs https://www.chargeprice.app/?poi_id=d0e51f7b-1bc9-4227-a22f-e17a1b1989ba&poi_source=chargeprice

**Comment by Altonss** [comment]
Thats's great, thanks for the update!
