### ISSUE TITLE
Map for charging stations

### ISSUE THREAD

**Issue by GITMichaelK** [johan12345/EVMap#237]
As far as I understood so far, a map showing nearby charging stations is only supported for GOOGLE maps. Is this correct?:
 * If so, is there any plan to allow OpenStreetMap, too?
 * If not, what do I have to to use OpenStreetMap, which is already on my device as [OSMAND~  ](https://f-droid.org/de/packages/net.osmand.plus/)

**Comment by Altonss** [comment]
> As far as I understood so far, a map showing nearby charging stations is only supported for GOOGLE maps. Is this correct?:
> 
>     * If so, is there any plan to allow OpenStreetMap, too?
> 
>     * If not, what do I have to to use OpenStreetMap, which is already on my device as [OSMAND~  ](https://f-droid.org/de/packages/net.osmand.plus/)

If you download the app from F-Droid, the map used is Openstreetmap :) https://f-droid.org/en/packages/net.vonforst.evmap

**Comment by GITMichaelK** [comment]
Thank you and Yes, I used the F-Droid Download. There are two options at the beginning:
 * GoingElectric.de (which I would prefer, DE-countries)
 * OpenChargeMa (worldwide, various qualities)
I had GoingElectric.de and came to GOOGLE. How to set it up correctly?

**Comment by johan12345** [comment]
The data source for *charging stations* is separate from the data source for *maps*. The former can be changed in the app's settings between Google Maps and OpenStreetMap (or, in the F-Droid version of the app it is always OpenStreetMap).

**Comment by Altonss** [comment]
> * I had GoingElectric.de and came to GOOGLE. How to set it up correctly?

I don't know how this is possible, have you maybe clicked on navigate to charger and your default navigation app is not Osmand but Google maps?

**Comment by GITMichaelK** [comment]
Yes, I clicked on navigate to charger. Where to define my default navigation app?

**Comment by Altonss** [comment]
> Yes, I clicked on navigate to charger. Where to define my default navigation app?

That is an Android system setting which is independent of EVMap

**Comment by GITMichaelK** [comment]
> That is an Android system setting
Yes, but WHERE  to define it?

**Comment by Altonss** [comment]
> > That is an Android system setting
> > Yes, but WHERE  to define it?

Sorry, but I don't know your exact device and software version. What I could advise you to do, is search information about this in your favorite search engine. I found this guide for example: https://www.androidauthority.com/change-default-apps-android-2-633572/

This issue can be closed then, as it's not about EVMap :)

**Comment by GITMichaelK** [comment]
It works now: I did a new install an with GoingElectric.de after clicking NAVIGATE, EVmap shows options for navigation, incl. OSMand. I tried it, works! I checked the option Standard-Nacigator for OSMand, works from now!
Thank you for your support!!!

**Comment by Altonss** [comment]
This issue could be closed now :)

**Comment by johan12345** [comment]
Thanks @Altonss for your help!
