### ISSUE TITLE
Charger name not displaying correctly/consistently

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#246]
Location: Porsche Zentrum Niederrhein

The bug appears when just clicking on the charger pin on the map, and appears on the small bottom info bar.

**Comment by johan12345** [comment]
Do you mean that while the charger is loading, a different name (of a previously selected charger) is displayed for a short time?
This is probably fixed in the next release with https://github.com/johan12345/EVMap/commit/eebb060f1a9ad39b820427ad61f1310aab68a275.

**Comment by johan12345** [comment]
There was also another fix in https://github.com/johan12345/EVMap/commit/89957ef73890765c9dd6eb87e28141b8d8385968 related to #247, which should also address such issues and will be part of the following update.

**Comment by Altonss** [comment]
> There was also another fix in [89957ef](https://github.com/johan12345/EVMap/commit/89957ef73890765c9dd6eb87e28141b8d8385968) related to #247, which should also address such issues and will be part of the following update.

Thanks a lot! I will just test out the next release and report bugs here, if I see something :)
