### ISSUE TITLE
Android Automotive: Various issues since update 1.4.x / Car App Library 1.3

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#254]
**Compass is not working**
I thought I had fixed this before, but a user reports it is not working in version 1.4.0.
I cannot reproduce it on the Emulator, it only occurs on a real car (Polestar 2 and Volvo XC40).

**Refresh button does not appear, "disabled" row state not working**
Also cannot reproduce this on the emulator.
*Update*: workarounds for these have been added with update 1.4.3, see below

**Comment by mb-software** [comment]
I can confirm that compass does not work in a polestar. Other sensor values are correct but direction only shows unknown.

**Comment by johan12345** [comment]
My current theory is that the car might report an outdated Car App API level to the app and thus it doesn't try to access the compass (API level 3 is required for compass, and 5 for some other features that users [also reported](https://polestar.fans/t/evmap-update/13549) as not working on a Polestar 2). 
@Ixam97 will help me debug this once he has picked up his Polestar.

See also: https://issuetracker.google.com/issues/260112181

**Comment by Ixam97** [comment]
I've now had some time to look at the debug data. On the real hardware API level 4 is reported, on the emulator however it is API level 6. Both Template Hosts are up to date.

Would this be an issue Google is responsible for, or would it more likely be Polestar themselves?

![image](https://user-images.githubusercontent.com/12702685/204104905-1d70c334-72f3-42ff-b7a9-c9dc5c21d628.png)
![image](https://user-images.githubusercontent.com/12702685/204104957-49315467-b542-4456-a263-517b3794d7e0.png)

**Comment by johan12345** [comment]
Thanks for testing! Okay, then the reported API level is definitely the reason why the refresh button is not appearing and the highlighting of own plans in the price comparison is not working. I would expect the issue to be on Google's side as the Template Host app is provided directly by them - so I've added this information in the [bug report](https://issuetracker.google.com/issues/260112181) in the Google Issue Tracker.

On the other hand, the compass (on the vehicle data page, and for the "only show chargers in driving direction" feature) should still work even when the car reports API level 4... could you confirm that it is not working for you? I can try to add some more debugging info for that.

**Comment by Ixam97** [comment]
> could you confirm that it is not working for you?

It indeed is not shown, but I couldn't test it while driving yet.

![image](https://user-images.githubusercontent.com/12702685/204107697-72d3d06e-0da2-43cb-bca0-c75c904474d3.png)

Oh and I also documented the actual version of the Template Host installed on the Car:

![image](https://user-images.githubusercontent.com/12702685/204107686-1e65c63c-0c35-4063-bb91-48a132a7bea6.png)

One thing I noticed: On the emulator, the app background ist filled with gray stripes. This is not the case in the car. The car uses Android 11, the emulator Android 10, so this might just be a visual adjustment. But maybe Polestar has implemented some template featuers differently in the emulator compared to the actual car.

**Comment by johan12345** [comment]
@Ixam97 and I figured out that [this workaround](https://github.com/johan12345/EVMap/commit/6d877e13e4fab597cbd42436720f1169ab16eba1) (i.e. simply ignoring the lower API level) re-enables the refresh button. This should be fixed with update 1.4.3, which is on its way to the Play Store now.

Still investigating the other issues.

**Comment by johan12345** [comment]
Tests with `GAME_ROTATION_VECTOR` were not successful so far - in https://github.com/johan12345/EVMap/commit/2166ac076a47a5cd6e0306d48b3665df158fbc2c I implemented a fallback to GPS-based direction detection instead (which will of course only work while moving). If that works okay on @Ixam97's car I will release it in the next update.

**Comment by Ixam97** [comment]
I now had the ability to look at the GPS-based direction. It gives back an angle, starting north going clockwise. I've tested it on this relatively straight road and got readings from 222° to 223°:

![image](https://user-images.githubusercontent.com/12702685/207595544-1f98cbd9-e3bc-43cc-af9a-8b3a922f3937.png)

**Comment by johan12345** [comment]
That sounds pretty good! So you were driving southwest on that road? Then 222-223° is correct, yes.

**Comment by johan12345** [comment]
Okay, thanks for testing! Then this should be fixed for now. Update 1.4.4 is on the way to all users now (after review from Google).
