### ISSUE TITLE
Weird "??" displayed before connector number when no real time status

### ISSUE THREAD

**Issue by Altonss** [johan12345/EVMap#257]
During the loading of the connector status (which somehow takes forever) or on connectors where there is no real-time status, weird "??" are displayed on my device before the connector amount.

Debug info:
 - Android 13
 - EVMap 1.4.0 from F-Droid

**Comment by johan12345** [comment]
Do you have a screenshot of this?
Is it occurring for all chargers? And with which data source?

**Comment by Altonss** [comment]
> Do you have a screenshot of this? Is it occurring for all chargers? And with which data source?

![Screenshot_20221112-194317](https://user-images.githubusercontent.com/66519591/201489845-0d84d8c6-21e5-4972-9060-294680e026d2.png)

It is occuring for all chargers that don't have real-time connecter status it seems (at least a lot of them, tried random ones), and with every data source.

**Comment by johan12345** [comment]
Hm, in that place there should usually be a times symbol (×). I can reproduce the problem, but only with the F-Droid build. Maybe it's an encoding issue on their side? (Cc @licaon-kter).

[This](https://github.com/johan12345/EVMap/blob/master/app/src/main/res/layout/item_connector.xml#L42) is where the symbol is used, the file is UTF-8 encoded. Maybe F-Droid interprets the source files with a different default encoding?

I'll try replacing the character with an escape sequence (`\u00D7`) to see whether that fixes the issue in the next update.

**Comment by licaon-kter** [comment]
Might have been an F-Droid issue, fixed by https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1259

**Comment by johan12345** [comment]
This seems to be fixed with the latest releases (1.4.1 and 1.4.2) on F-Droid.
