### ISSUE TITLE
Make a Google Maps-free version of the App

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#36]
It has been requested a few times to build a version of this app that uses OpenStreetMap instead of Google Maps - which would then be fully open source and suitable for inclusion in [F-Droid](https://f-droid.org/). It would also be able to run on Android devices without Google Play Services (e.g. custom ROMs).

**In principle, I would like this to happen, but** it causes a few problems:

- OSM data are free, but hosting is not
    - Freely available [tile servers](https://wiki.openstreetmap.org/wiki/Tile_servers) have strict usage policies, e.g. OSM themselves do not allow distributing apps that use their tile server. I haven't found a usage policy for [Carto](https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/18/137191/90018.png) [basemaps](https://carto.com/help/building-maps/basemap-list/), which e.g. [wo-ist-markt](https://github.com/wo-ist-markt/wo-ist-markt.github.io/blob/39c5d4b42aca93ef483c18390049e0602a0b3104/js/main.js#L6) seems to be using.
    - Commercial tile providers like Mapbox and MapTiler have free plans, but only up to a certain limit.
    - GoingElectric.de is also hosting [OSM tiles](https://api.goingelectric.de/maps/styles/osm-bright/16/34609/20936.auto?key=31816b3da82dd54daad285122e84f455) themselves. They seem to be available using the same API keys as the GE charging stations API, but this is not documented anywhere and therefore probably not intended to be used by external applications.
    - We could host map tiles ourselves, but this is costly due to the high hardware requirements.
    - Google Maps, on the other hand, is currently free for all Android Apps without any usage limits.
- Google Maps provides some features which are not easily replacable with OSM data (satellite images, traffic data). These would then not be available in the app anymore.
- Maps is not the only thing in the app which uses Google services. Place search ("geocoding") would also need to be replaced, and APIs for this cost money as well.
Additionally, we would need to replace [Fused Location Provider](https://developers.google.com/location-context/fused-location-provider) API and Google Play In-App purchases, but that would not be very complicated.
- I wouldn't want to completely replace Google Maps, but instead offer both Google Maps and OSM in parallel. But this would also difficult to maintain due to the completely different APIs of Google Maps and osmdroid. https://github.com/sharenowTech/AnyMaps looks a possible solution, but it seems to not be actively maintained anymore.

**Because of all these issues, I will not actively work on this at the moment.** If someone is interested, feel free to search solutions to these problems and start a PR.

**Comment by johan12345** [comment]
TomTom Maps might be an option. https://developer.tomtom.com/store/maps-api

**Comment by johan12345** [comment]
These seem to be the policies for the Carto maps: http://web.archive.org/web/20171115130721/https://carto.com/location-data-services/basemaps/

**Comment by johan12345** [comment]
I actually started working on this. The current approach is to use a [fork of AnyMaps](https://github.com/johan12345/AnyMaps), in which I have done various updates to make it work correctly.

**Comment by johan12345** [comment]
Done. :)

**Comment by jwiesel** [comment]
Thanks for giving the background info on the use of GoogleMaps.
I can imagine various users of F-droid try to avoid Google services to increase their privacy and will therefore not use the app, although the idea is great! Using GoingElectric on a smartphone display while searching for the next available fast charging point on the planned route can be tedious!

I respect your decision and the openness to integrate a possible PR from someone else. Regarding your remarks:
* Replacing the geolocation service of google by a privacy friendly service is not that difficult from my point of view. There would simply need to be an api endpoint hosted somewhere to call the Google Geocoding api. The EVMap android app would then call that api endpoint and by that the requests would be anonymous (as they all come from a central place without user identification).
* Regarding rendering of the map I can imagine various other "map" apps on F-Droid found a solution already (e.g. StreetComplete). Maybe such a solution can even be reused for EVMap as they are open source.

**Comment by johan12345** [comment]
@jwiesel Have you read the remaining comments below? The version of EVMap that is now available on F-Droid uses OpenStreetMap data and geocoding APIs from Mapbox, so it is independent of Google Play Services.

**Comment by jwiesel** [comment]
@johan12345 : Oooh, sorry! I seem to have over-read that! Great news! Thanks!
