### ISSUE TITLE
Android for Cars/Auto

### ISSUE THREAD

**Issue by voneinem** [johan12345/EVMap#39]
This is a great app!
It would be really cool if you could run it as phone projection in Android for Cars/Auto.

**Comment by johan12345** [comment]
Thanks!

I would also really like this, unfortunately Google still doesn't allow 3rd party apps in Android Auto, other than media apps (with a restricted interface for selecting media items) and messaging app notifications. The same seems to be true for Android Automotive OS (i.e. the native Android OS used in the newest Volvo and Polestar EVs). There are [design guidelines](https://designguidelines.withgoogle.com/android-auto/custom-apps/custom-app-anatomy.html) in place, but no developer documentation.

**Comment by voneinem** [comment]
Yeah, I've seen this. Though it seems to be possible to develop a custom Android Auto app and run it if you know how to enable unknown sources in the Android Auto developer settings. At least for my E-Niro I know how this can be done.
[My Journey on developing a Custom Android Auto app](https://medium.com/@dirkvranckaert/my-journey-on-developing-a-custom-android-auto-app-de4fb7777fd1)
I do not have a lot of experience with Android app development but I could try to contribute.

**Comment by johan12345** [comment]
Do you know that this still works with the current versions of Android Auto? That blogpost is from 2017, and I also saw that there used to be an unofficial SDK at https://github.com/martoreto/aauto-sdk (see also the forum thread linked there), but they say it's not working anymore with Android Auto 3.0 and above.

**Comment by voneinem** [comment]
Oh, that's disappointing!

**Comment by johan12345** [comment]
https://android-developers.googleblog.com/2020/08/android-for-cars.html

> Our early access partners will be releasing new apps to their beta testers by the end of this year. Pending additional testing and feedback, we then plan to make these APIs publicly available for all developers to build Android Auto apps in these categories.

**Comment by voneinem** [comment]
Wow! That gives hope!
PlugShare and ChargePoint mentioned as early access. They are not half as good as EVMap.
Can't wait for the public API!

**Comment by johan12345** [comment]
I have asked at https://groups.google.com/a/android.com/g/automotive-developers/c/bleTzOdS_Dg if it is possible to join the early access program (i.e. before next year), but we shouldn't get our hopes too high...

**Comment by johan12345** [comment]
The library used for building such apps seems to be available in a public beta now, though it's not yet allowed to publish apps that use it:
https://android-developers.googleblog.com/2020/10/introducing-android-for-cars-app-library.html´
https://developer.android.com/training/cars/navigation

**Comment by voneinem** [comment]
Great! Seems like it's really moving forward! 
I will give it a try myself. Happy to contribute - even if it would just be testing.

ps.: the link above has an extra ´ this link works:
[https://android-developers.googleblog.com/2020/10/introducing-android-for-cars-app-library.html](https://android-developers.googleblog.com/2020/10/introducing-android-for-cars-app-library.html)

**Comment by johan12345** [comment]
That sounds great, thanks! I already added the "hello world" example for the CarAppService on the https://github.com/johan12345/EVMap/tree/android-auto branch, but couldn't get it to run yet (Desktop headunit keeps displaying "waiting for phone").

**Comment by johan12345** [comment]
Okay, I needed to go back to the Android Auto app and accept some permissions, then the desktop headunit works.

**Comment by johan12345** [comment]
This is the current state:
![image](https://user-images.githubusercontent.com/5310424/97231999-b3b29000-17dc-11eb-8e8c-d21916755e91.png)

i.e. it can show a view with a list of chargers (not yet loaded from the API).
To draw a map in the background, it seems that we need to manually implement rendering the map to a Canvas (probably by creating a GoogleMap view and manually drawing that) - Apart from the [example here](https://github.com/android/car-samples/blob/master/Auto/car_app_library/showcase/src/main/java/com/google/android/libraries/car/app/samples/showcase/navigation/SurfaceRenderer.java), which seems to just draw some dummy text, I haven't found any examples of this yet (which makes sensee as this API is extremely new).

**Comment by voneinem** [comment]
This is already amazing!
I will give it a try. I haven't done a Android programming until now but I will make it a start.

**Comment by johan12345** [comment]
Okay, apparently we don't need to render the map ourselves, but can use the [PlaceListMapTemplate](https://developer.android.com/reference/com/google/android/libraries/car/app/model/PlaceListMapTemplate)... that just wasn't well referenced in the documentation.

**Comment by johan12345** [comment]
see a6f3c5352fd7182130240f9d3a2fe06be53d6356

**Comment by johan12345** [comment]
I worked on this a bit over the Christmas days (see the android-auto branch):
![overview](https://user-images.githubusercontent.com/5310424/103295663-b906a380-49f4-11eb-8b5a-4eae27fac24d.png)
![detail](https://user-images.githubusercontent.com/5310424/103295661-b86e0d00-49f4-11eb-90a5-1cb7d34c3137.png)

So far it only shows the chargers close by, it would be nice to add another screen before where one can choose between showing the favorites or the closest chargers.

**Comment by johan12345** [comment]
I have put an internal testing version of this on the Play Store now, if you would like I can add you to that so that you can test on your car - I just need your Google Account email address (send to evmap@vonforst.net).

Public release is still not possible, the latest announcement from Google is [here](https://android-developers.googleblog.com/2020/12/opening-google-play-store-for-more-car.html).

**Comment by voneinem** [comment]
I installed the testing version and connected to my Kia Niro EV.
The app showed nicely on my head unit display. I could select a charging station from near by or favorites.
"Navigieren" started Google Maps Navigation right away.
"In App öffnen" opened EVMaps on my phone and selected the station.
I'm very curios which features will be added soon for Android Cars and when it will available to the public.
 
![IMG_20210103_192402](https://user-images.githubusercontent.com/1850001/103486593-3e2bf700-4dff-11eb-8309-a26f0c1bf08d.jpg)
![IMG_20210103_192446](https://user-images.githubusercontent.com/1850001/103486595-41bf7e00-4dff-11eb-8ff1-1a4acc8f6c29.jpg)
![IMG_20210103_192527](https://user-images.githubusercontent.com/1850001/103486597-45530500-4dff-11eb-8ec4-3351af5a6e13.jpg)
![IMG_20210103_192601](https://user-images.githubusercontent.com/1850001/103486601-484df580-4dff-11eb-906d-926bbd404114.jpg)

**Comment by F3000** [comment]
Android Auto: Google erlaubt offene App-Tests fürs Auto https://www.deskmodder.de/blog/2021/01/28/android-auto-google-erlaubt-offene-app-tests-fuers-auto/

**Comment by johan12345** [comment]
Yep, it's already available in the public beta - see https://www.goingelectric.de/forum/viewtopic.php?p=1496521&sid=9e5acb1e1141a956025026d7facbad8c#p1496521

**Comment by johan12345** [comment]
Android Auto apps can now be released publically in the Play Store. So I will now rebase the android-auto branch against `master` and make an update to the public version of the app.

**Comment by gogamid** [comment]
@johan12345 I see that you have implemented PlaceListMapTemplate that uses automatically Google Maps on the background. This will work on Automotive OS with Google Services (like Polestar and Volvo). But when you run this app on AOSP Automotive, background Map wouldn’t be available. I wanted to ask if you found a way to render background map manually in PlaceListMapTemplate?

**Comment by johan12345** [comment]
Hi @gogamid! No, there is no way to render the background map manually in PlaceListMapTemplate, that requires PlaceListNavigationTemplate (which is only available for navigation apps, not POI apps).

Regarding AOSP Android Automotive, I would assume that out of the box, templated apps wouldn't work at all, because they require the "Google Automotive App Host". You can run "normal" Android apps on Android Automotive though (such as e.g. the FOSS flavor of EVMap) - they just aren't allowed in the Play Store for driver safety reasons.

**Comment by gogamid** [comment]
@johan12345 there is update from google. Now you can embed „AOSP Automotive App Host“ to AOSP(see [AOSP Host](https://source.android.com/docs/devices/automotive/hmi/aosp_host) ). Then you can run  templated app examples on AOSP like helloworld, showcase, navigation and places ([Car-samples](https://github.com/android/car-samples) )

I have to now figure out how to integrate any map into PlaceListMapTemplate to show only those location markers on map. If you have any guidelines/update let me know, i appreciate that 😊

**Comment by johan12345** [comment]
@gogamid Then I guess I would take a look into the source code of that AOSP Automotive App Host and try to replace Google Maps with another maps SDK. I have no experience with that, I have only seen this template engine from the app developer side so far 😉

**Comment by gogamid** [comment]
@johan12345 Finally, I could integrate third-party map called Mapbox to Automotive OS without Google Services, you can check it out:
https://github.com/gogamid/mapbox-automotive-integration/tree/main
![Screenshot_1667862474](https://user-images.githubusercontent.com/36050790/200436137-d727ceae-70b3-4dc3-a571-0de60aa543c3.png)

I have used `PlaceListNavigationTemplate` instead of `PlaceListTemplate`.

**Comment by johan12345** [comment]
Nice! As you know this is currently not a solution for EVMap as Google does not permit the use of `PlaceListNavigationTemplate` in apps that are not in the navigation category (EVMap doesn't provide any navigation functionality so far, so it's only a POI app). But I guess making the `PlaceListMapTemplate` usable with a custom map might also be possible if you modify the AOSP template host app, I see there are some stub classes in there that need to be implemented to provide a map implementation: https://android.googlesource.com/platform/packages/apps/Car/Templates/+/refs/heads/master/Host/app/src/main/java/com/android/car/templates/host/view/widgets/maps
-> So if manufacturers would implement those stub classes for their template host, I could build a variant of EVMap for Android Automotive without Google Services (which should not be too hard) and it should work.

**Comment by gogamid** [comment]
@johan12345 that is excellent observation, I did not think about checking the source code of template host. Thank you for that insight!
Yes, you are right, in that case Map of manufacturer will be displayed in `PlaceListMapTemplate` screen instead of Google Maps.

**Comment by windlov2** [comment]
@gogamid, @johan12345 
I am developing POI App at Pixel AAOS Ref. phone that is without GAS as you know.
So, I'm looking for how to display a map when my POI app uses a PlaceListMapTemplate.
How to display the custom map at your test app?
Do you customize or integrate your own AOSP Host App? then how?

I wait your any feedback for me. Thanks

**Comment by gogamid** [comment]
@windlov2 
From my experience, there are two ways of displaying a custom map in an Automotive AOSP Host:

1.  Get the open source code for AOSP Host from repo mentioned [here](https://source.android.com/docs/devices/automotive/hmi/aosp_host). Change the [map part](https://android.googlesource.com/platform/packages/apps/Car/Templates/+/refs/heads/master/Host/app/src/main/java/com/android/car/templates/host/view/widgets/maps) as @johan12345 mentioned above(I did not figure it out yet how). Then build and install your custom AOSP Host to the device. Now, all your `PlaceListMapTemplate` Screens will be showing your custom map.
2. Instead of using `PlaceListMapTemplate` use `PlaceListNavigationTemplate`, which is in my opinion same screens, only difference is that you have to declare your app as a `Navigation App` not `POI`.  Then integrate `mapbox` to your app. 
Now, you can install app on a device with any AOSP Host, it will show Mapbox map. This i have done it [here](https://github.com/gogamid/mapbox-automotive-integration/tree/main).

Hope that helps!

**Comment by windlov2** [comment]
@gogamid

Oh! thank you very much, gogamid.
Your answer is a great help.
In my project, I should develop POI app (not navigation app). so, I'll use first option of yours
