### ISSUE TITLE
Make app available in F-Droid

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#40]
see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7233

**Comment by johan12345** [comment]
It is now available: https://f-droid.org/en/packages/net.vonforst.evmap/

**Comment by IzzySoft** [comment]
@johan12345 as it's in "F-Droid proper" now: do you want me to keep it in my repo? I usually remove it at this point to avoid confusion – unless there's special demand to keep it (eg for test versions).

**Comment by johan12345** [comment]
@IzzySoft I think it's fine if you remove it. The F-Droid client should then redirect to the version in the the official F-Droid repository automatically, as it's the same package name, right? Users might just need to reinstall due to the different signature.

**Comment by IzzySoft** [comment]
Yes, exactly. And should the need arise, I can add it back anytime, just let me know!

Thanks to you!
