### ISSUE TITLE
Include Chargelog (Ladelog)

### ISSUE THREAD

**Issue by voneinem** [johan12345/EVMap#41]
It would be nice to see the chargelog (Ladelog) in the details.
Recent successful entries indicate a working charger.

**Comment by johan12345** [comment]
There is an API endpoint for the charging log, but it's not part of the [documented GoingElectric API](https://www.goingelectric.de/stromtankstellen/api/docs/).

As the [terms of usage](https://www.goingelectric.de/stromtankstellen/api/terms/) say it is only allowed to use the data provided by the API ("Es dürfen ausschließlich die über die Schnittstelle bereitgestellten Daten verwendet werden.") we are not allowed to use these data in the app.

Some other apps (e.g. ChargEV on iOS) solve this problem by providing an own check-in service independent of GoingElectric's - but I think building another separate database is not a good idea. I also found that [AirElectric](https://play.google.com/store/apps/details?id=io.airelectric) claims to have GoingElectric charging log in the app, but I couldn't find it anywhere - maybe they needed to remove it?

According to Guy, the operator of the GoingElectric site, a new version of the API is in development, but there is no ETA on that and it will probably not be free anymore.

**Comment by voneinem** [comment]
I created this request based on thread on [Twitter](https://twitter.com/alles_fliesset/status/1294909580670050305).
When I look at the charging log of the chargers I usually use the log might contain less than 5% of the usage I'm seeing there.
Anyhow it is possible to click on the GoingElectric link in the app to see the log.
This can be closed.
