### ISSUE TITLE
Feature request : In-app browser support

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#49]
until now every time I click on a link a separated browser is opened .

Is this possible to add a in app browser ?

**Comment by johan12345** [comment]
If you have a device with Chrome installed, it should already use [Chrome custom tabs](https://developer.chrome.com/multidevice/android/customtabs) as an in-app browser. You should be able to recognize them by the green title bar.

**Comment by F3000** [comment]
The behavior on my device is following :

First I see this "choosing screen" 

![image](https://user-images.githubusercontent.com/8161283/91059516-201ce180-e62a-11ea-96d7-ab62a945db78.jpeg)


After that I see your mentioned chrome feature .
![image](https://user-images.githubusercontent.com/8161283/91059584-32971b00-e62a-11ea-8847-4c78f9784cfd.jpe)


The only workaround is to choose "Immer" .

Ok I thought that android has a similar function for that like iOS .
Here the in appp function is like a safari view in the app.

**Comment by johan12345** [comment]
> Here the in appp function is like a safari view in the app.

that is what Chrome Custom Tabs is supposed to be for Android

Looking at the icons your phone is showing, maybe it doesn't work because you have installed Chrome under a work profile and EVMap under a private profile, or the other way round? Maybe that is interfering with Chrome Custom Tabs.

**Comment by F3000** [comment]
Both apps are in the container. But access is under the hood also a chromium browser .

Maybe that's the point . But with chosen "immer" it works fine
