### ISSUE TITLE
Bug : change of map style leads to crash the app

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#50]
Device : Samsung S10 with android 10 (patch 1.Juni) 

How to reproduce :
- click on "layer" button in the top right corner 

- touch anywhere in the app to scale the map 

- app is freezing now and needs to be restarted

**Comment by johan12345** [comment]
Hm, I can't reproduce that at the moment. Is this happening with Google Maps, Mapbox or both?

**Comment by F3000** [comment]
I think I have the error:


- try to open the layer menu 
- tip on "Kartentyp" 
- after that the app is freezing 

Both with Gmaps and OSM . 


Two other questions related to this :

1) how can I hide the "layer/menu" pop up ? 

2) when using OSM maps I would deactivate the button "show traffic" because it kids google maps

**Comment by johan12345** [comment]
> how can I hide the "layer/menu" pop up ?

By tapping somewhere on the map (not on a charging station) or pressing the "back" button of your smartphone.

> when using OSM maps I would deactivate the button "show traffic" because it kids google maps

What do you mean with that? Mapbox (the OSM provider that we use) does provide their own traffic data, this is not from Google.

**Comment by F3000** [comment]
The traffic data from OSM look identical so I thought it was a bug . 


Yes tested it with tapping somewhere .
On my device a liitke bit laggy but it works

**Comment by johan12345** [comment]
I now added a button to explicitly close the layers menu, this should make it more obvious. I cannot reproduce any crash caused by opening the layers menu or changing the map style.
