### ISSUE TITLE
Cosmetic bug : layer button is placed over search bar

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#51]
Seen this on my S10 

![image](https://user-images.githubusercontent.com/8161283/91041883-1aff6880-e611-11ea-8b8f-c19bef898754.jpeg)

**Comment by johan12345** [comment]
Strange... I will investigate.

**Comment by johan12345** [comment]
This seems to be caused by the higher-than-usual status bar due to the camera cutout in the display. I fixed it now, but only remembered to do so after releasing an update... so this will have to wait for the next one.

**Comment by F3000** [comment]
> This seems to be caused by the higher-than-usual status bar due to the camera cutout in the display. I fixed it now, but only remembered to do so after releasing an update... so this will have to wait for the next one.

So maybe a specific Samsung problem because for the camera .


Thanks for fixing 😊

**Comment by F3000** [comment]
Working now 👌
