### ISSUE TITLE
Feature request : add “station availability” in map screen

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#52]
Is it possible to change the color of the lightning ⚡️ in the map marker ? 

E.g. 

- red lightning: station full 
- green lightning : station empty 
- yellow lightning : half full (for stations with multiple slots) 

I think it is much easier than to see if the station is empty or not 👍

**Comment by johan12345** [comment]
To match a charging station entry from GoingElectric with the availability data from NewMotion, the app uses multiple pieces of information, such as the operator and the number, type and power of available connectors (as the location usually doesn't match exactly). This is only possible with the "detailed" request of the NewMotion API, where only one station can be requested at a time.

So to requesting the availabilities for many stations in the map view would cause many requests at the same time, which consumes a larger amount of data and also sometimes leads to NewMotion returning an error (probably to prevent bots from collecting large amounts of data through their API).

A compromise could be to show the availability (in a compact view like in the favorites list) directly after tapping on the charging station, and not only after scrolling up to see the connectors.

**Comment by F3000** [comment]
The compromise is good 👍


Here is an example from a iOS app :

When a user zoom out the the stations are summarized without displaying availability.
![image](https://user-images.githubusercontent.com/8161283/91072274-89f0b780-e639-11ea-863d-b11c1249f515.jpeg)


User zoom in and see the availability of each station .
I think this reduce data .
![image](https://user-images.githubusercontent.com/8161283/91072395-bd334680-e639-11ea-9b98-3fe975c5cb8d.jpeg)


Does this makes sense ?

**Comment by johan12345** [comment]
> Here is an example from a iOS app :

Do you know what data that app uses for chargers and availability? Is it one from the charger operators/payment providers or is it data from GoingElectric?
If I would only be using e.g. NewMotion data this would be no problem, the challenging thing is to combine that with GE.

**Comment by F3000** [comment]
Good question 😀

The main app is this one here :

https://apps.apple.com/de/app/laden/id1436430456


The screenshot above is from the beta version I will test in the moment . 
They have renamed their product .

More infos here : 
https://pumpapp.co/


Maybe a hint :
I wrote to them some weeks ago that the "Allego" stations in Berlin won't show any information .
They have fixed this quickly on the server side . 

Would you contact them from to developer to developer or should I ask ? (They speak german too) 

For inspiration I can send you some screenshots from the apps when you don't have an iOS device .

**Comment by johan12345** [comment]
> Maybe a hint :
> I wrote to them some weeks ago that the "Allego" stations in Berlin won't show any information .
> They have fixed this quickly on the server side .

Hm, okay, so probably they operate an own server that collects and distributes the charger information from GoingElectric and the availability data. I would not like to do this for EVMap at the moment to keep the complexity low. At some point there will be a new GoingElectric API (with some new features), so things will need to be rewritten anyway.
