### ISSUE TITLE
Bug : version 0.3.4 doesn’t start on android 10

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#54]
Hi ,

today I received the update . But I can't start the anymore .

Error :
App crashed repeatedly

**Comment by johan12345** [comment]
Sorry, that was indeed an error on my side. I have uploaded a new release which should fix the problem (see https://github.com/johan12345/EVMap/commit/87421e450ae41e6f5248008b42374f9a3eb50a06), I hope Google's review process doesn't take so long this time.

**Comment by F3000** [comment]
Thanks. Will test it out 👍

**Comment by F3000** [comment]
Working now 👌
