### ISSUE TITLE
Feature request : open error log directly

### ISSUE THREAD

**Issue by F3000** [johan12345/EVMap#55]
Hi ,

is it possible when a user is clicking on "Störungsmeldung" in the station main overview that the in app browser open following section of the site :

![image](https://user-images.githubusercontent.com/8161283/91636415-96da2600-ea00-11ea-99c4-0226fb4ecf68.jpeg)

Otherwise the user have to scroll through the GE site

**Comment by johan12345** [comment]
No, I think there is no way to directly open the fault log directly with an URL parameter etc. The fault log button doesn't even have an ID attached to it in HTML, so it is not possible to scroll to it directly.

The charging and fault logs are loaded through an API on the website, but that's not officially documented, so GoingElectric's API terms of usage prevent us from using them directly in the app.
