### ISSUE TITLE
Feature request: Multiple filters

### ISSUE THREAD

**Issue by theoriginalgri** [johan12345/EVMap#58]
Right now, I'm using the filters only for trips (DC and a few providers). Having the option to at least define two filters (AC for example) and select between them and none would be a great feature in my point of view.

**Comment by johan12345** [comment]
Yes, this is already planned (#16) and I started working on it on the `filter-profiles` branch. Just don't have so much time to work on EVMap at the moment... :)

**Comment by johan12345** [comment]
Closing as duplicate of #16
