### ISSUE TITLE
Android Auto: Allow to select filter profiles (saved in the app)

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#72]
Good idea from the [Goingelectric forum](https://www.goingelectric.de/forum/viewtopic.php?p=1498670#p1498670). This could be implemented as an action button in the "nearby chargers" view which then shows a list of the available filter profiles.

Depending on the active filters by plug type and power, the availability data shown in the list (e.g. 3/3) should also be filtered - just like it is already implemented in the main app.

@voneinem would you be interested in working on this?

**Comment by voneinem** [comment]
Challenge accepted!
