### ISSUE TITLE
Edit favorites directly

### ISSUE THREAD

**Issue by corwin42** [johan12345/EVMap#75]
It would be nice to have the possibility to delete favorites directly in the favorites list.

Long press on a favorite should change the action bar to a contextual actionbar with delete option. Then one or more entries should be selectable and deletable at once.

Currently you have to change each entry quite complicated by going to the entry and uncheck the favorite icon.

**Comment by johan12345** [comment]
Agreed! Alternatively we could use a swipe-to-delete, like it is already implemented for the list of filter profiles.

Would you like to work on this?
