### ISSUE TITLE
Support for other countries, e.g. through OpenChargeMap

### ISSUE THREAD

**Issue by Kreuger** [johan12345/EVMap#81]
Would it be possible to add support for other countries? As someone from Canada, I would love for this app to have support here. Maybe a way to change the API used for sourcing the chargers?

**Comment by johan12345** [comment]
Hi! Sure, in principle that would be possible - would just need some additional abstraction in the code to convert the data from different APIs into a common format and an option in the settings to switch between the APIs. Would you like to work on a PR for this?

Do you know any good open data sources for chargers in Canada? For example, https://openchargemap.org/ might be an option, as their API is free to use.

**Comment by Kreuger** [comment]
Im not a coder so I dont know if I can help with a PR for this. But I will look into free APIs.

**Comment by johan12345** [comment]
> Edit: Heres a start.
> https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/

Hm, it looks like that API provides much less detailed information than we get for European chargers from GoingElectric.de (e.g. no information on the available power of the charger). And it can't be updated by the community if there is a charger missing or by adding more detailed descriptions and photos. OpenChargeMap seems to have some more data, and it seems like the charging stations listed there are also partially obtained from the NREL...

**Comment by Kreuger** [comment]
Fair enough. I havent looked at open charge map. There are a few apps available on the play store but most of them you have to request API access and I feel like that would either go against the FOSS principal and/or cost money.

**Comment by roshavagarga** [comment]
@johan12345 I'd also like to chip in. I have managed to find one general source for [Bulgaria](https://vsichkotok.bg/), but as far as I can see, it offers no way to get the data automatically. I'd be interested in inputting the data in a way that it's accessible and as far as I can see, that means adding it to goingelectric.de and chargeprice.app, but the former does not seem to have an English version and my German is, sadly, nonexistent. Any way I can contribute to something so you can make use of the info?

**Comment by johan12345** [comment]
Yeah, unfortunately there is no english version of goingelectric.de, as far as I know. Regarding chargeprice.app, I think they are at least planning to support OpenChargeMap as a data source (as that is listed as one of the possible sources in their [API docs](https://github.com/chargeprice/chargeprice-api-docs/blob/master/api/v1/charge_prices/index.md)). So I guess adding OpenChargeMap as an alternative source to EVMap as well would probably make sense.

Do you by any chance have any coding experience @roshavagarga, so you could help with the implementation of the OpenChargeMap API into EVMap? Of course, contributing information about the Bulgarian chargers on OpenChargeMap would then also make sense.

**Comment by roshavagarga** [comment]
Sadly, I'm not a dev in any way, just wanted to find out anything I could add information to (platform/website) that you could then use :) Hmm, since GE.de is German-only, that pretty much means there's no options I guess.

**Comment by johan12345** [comment]
Small update: I have started to work on implementing OpenChargeMap as a data source for EVMap (so that one can switch between GoingElectric.de and OpenChargeMap in the app settings, see PR #96 ). It is already working quite well, the main thing that is still missing is support for filters.

Here is, for example, a screenshot of central Toronto, where GoingElectric has no chargers listed:
![Screenshot_1625312055](https://user-images.githubusercontent.com/5310424/124352871-7754f080-dc03-11eb-80a0-65886fb83fc2.png)

The real-time availability and price comparison features work with OpenChargeMap as well, at least for chargers in Europe. Other countries may not work if not supported by [NewMotion](https://my.newmotion.com/) and [Chargeprice](https://www.chargeprice.app/), respectively.

Cc @Kreuger , @roshavagarga

**Comment by Kreuger** [comment]
Wow thats awesome. Thank you!

**Comment by johan12345** [comment]
I have just uploaded a new release with OpenChargeMap support to the beta channel on Google Play. You can register at https://play.google.com/apps/testing/net.vonforst.evmap to receive it after Google reviewed it (usually takes just a few hours). It will also be available on F-Droid as soon as their build server builds it, which can take a couple of days.

@Kreuger , @roshavagarga

**Comment by Kreuger** [comment]
Great, thanks for your work.

**Comment by johan12345** [comment]
@fhvyhjriur I don't think this is an issue in this case. It is a screenshot of EVMap for showing functionality of the app, not a screenshot directly taken from the Google Maps website. Numerous apps that use Google Maps data show screenshots on the Play Store or on their websites. Google also [explicitly allows](https://www.google.com/intl/en-GB_ALL/permissions/geoguidelines/) using imagery produced using their APIs for advertisement.
