### ISSUE TITLE
Some bugs with Chargeprice integration

### ISSUE THREAD

**Issue by kepppfeff** [johan12345/EVMap#82]
I have found some bugs related to the chargeprice integration (I hope it is okay to mention all in one issue):
- If I choose Renault ZOE Q210 as my vehicle (which has no DC charging), then open a triple charger, the app will crash when opening the price comparison window (if CCS or CHAdeMO is the preset plug on the left side).
- the prices seem to already reload while the SOC-slider is being moved. They should reload only after adjusting the slider to a new position.
- if I change my vehicle, the old vehicle will still be visible in the settings until I leave the settings and re-open them.
- the two filtering options for price comparison in the settings are cut off, I only see "Nur Tarife ohne monatliche.." and "Exklusive Energiekunden-Ta..".
Nevertheless, the chargeprice integration is already very nice! :-) Thanks for the great app!

**Comment by johan12345** [comment]
Thanks for the detailed comments! I'll fix them in the next update. It might require re-selecting the vehicle after the update, as the compatible connectors need to be saved locally for the crash to be avoided.

**Comment by johan12345** [comment]
The fixes are included in the update 0.7.1, which should appear in the next few hours.
