### ISSUE TITLE
Use OpenStreetMap (instead of Google Maps)

### ISSUE THREAD

**Issue by petrarca-arezzo** [johan12345/EVMap#83]
I would like to see EVMap to rather use OpenStreetMap (OSM) instead of Google Maps. OSM is free data, does not track users, is open source and usually has better map quality than Google.

**Comment by johan12345** [comment]
That is already implemented. You can switch to Openstreetmap (Mapbox) in the app settings. The version of the app available on F-Droid uses Mapbox exclusively.
