### ISSUE TITLE
Enhancements Chargeprice Interface

### ISSUE THREAD

**Issue by ericszimmermann** [johan12345/EVMap#86]
There are some things to improve the Chargeprice usage:
-Foremost: Save the Charging levels (charge from-to): It always resets to 20%-to-80%, but I only charge CCS to 70%.
-define Chargingcards to be shown: there are multiple cards I can not get, because they are only Distributed in Germany.
-ablitiy to change the currency to CHF and ohters.

Sincerely Eric

**Comment by johan12345** [comment]
Thanks! Yes, adding a selection of charging cards to be shown makes sense and is planned for a future update.

Saving the charging levels is also a good idea, and a setting for the currency of course is also necessary (I thing I overlooked that and simply hardcoded it to EUR, thanks for the heads-up!)

**Comment by johan12345** [comment]
These improvements are all implemented in the upcoming release 0.7.2 👍
