### ISSUE TITLE
Filter function

### ISSUE THREAD

**Issue by johan12345** [johan12345/EVMap#9]
- [x] Filter by connector type
- [x] Filter by power
- [x] Filter by minimum number of connectors
- [x] Filter by compatible charging cards/apps
- [x] only show stations with free charging
- [x] only show stations with free parking
- [x] Exclude CPOs (e.g. show all charging stations except Ionity)

**Comment by TweetsOfNiklas** [comment]
Maybe also:
Filter by price (free/not free)
Exclude CPOs (e.g. show all charging stations except Ionity)

**Comment by johan12345** [comment]
yes, makes sense!

**Comment by johan12345** [comment]
all filters are now implemented.
