### ISSUE TITLE
Issues opening a shared location

### ISSUE THREAD

**Issue by MisterY** [johan12345/EVMap#90]
Similar to #79, I'm trying to use EVMap as the destination for a shared address. For example, in PlugShare, open a charger details, then tap on the map/location to open it. 
When I use OsmAnd as the destination app, it will open the correct location (not the first time, interestingly!). But if I choose EV Map, it will stay on the default start screen, zoomed out.

This is an interesting feature to quickly compare the chargers between PlugShare and GoingElectric. Hopefully a day will come when the backends will share this info automatically. 
But it's more likely that these apps will become obsolete by then, since there will be enough chargers around. :D

**Comment by johan12345** [comment]
Hmmm... In principle, since #79 is fixed, EVMap should understand shared locations both as latitude/longitude coordinates as well as street addresses. But maybe PlugShare uses yet a different format...

**Comment by MisterY** [comment]
If I use a public transport app, it receives `44.208969,17.918028`.
OsmAnd was confused when opening the link the first time but the next time got better. Now shows the correct location but I can't tell what exactly it receives. I'd assume the same?
