### ISSUE TITLE
Notification when a charger becomes available

### ISSUE THREAD

**Issue by mhantsch** [johan12345/EVMap#94]
As a EV driver parked close to a busy charger,
I would like to get a notification when a charger becomes available,
So that I can move my car to the charger and plug in.

My use case: There is a public charger right in front of my workplace, but often it is occupied when I arrive at work. I would like to get a notification during the day when the charger becomes available, so I can plug in my car (only takes me a few minutes to walk down and move the car) and charge for the rest of the day.

So I would select the charger and tap a button "Notify me when available". That button may toggle to become "Stop notifying me". When turned on, EVMap would periodically check the charger status, and push a notification when at least 1 charge port is available again.

**Comment by johan12345** [comment]
Yes, this is a good idea! We already have issue #42 which is basically the same thing, so I'm closing this as a duplicate.
